# Generated by Django 2.2.1 on 2019-05-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=200, verbose_name='EVENT NAME')),
                ('event_start', models.DateTimeField(verbose_name='START TIME')),
                ('event_end', models.DateTimeField(verbose_name='END TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(auto_created=True)),
                ('ticket_name', models.CharField(default='', max_length=200, verbose_name='TICKET NAME')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
        ),
    ]
