# Generated by Django 2.2.1 on 2019-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190524_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(max_length=200, verbose_name='TICKET NAME'),
        ),
    ]
