# Generated by Django 2.2.1 on 2019-05-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190524_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
    ]
